version: "3.9"

services:
#  web:
#    build:
#      context: .
#      dockerfile: ./docker-build/shop/Dockerfile
#    environment:
#      CONFIG: ProductionConfig
#      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://username:passwd!@pg:5432/blog
#    ports:
#      - "8000:80"
#    depends_on:
#      pg:
#        condition: service_healthy
  pg:
    image: postgres
    environment:
      POSTGRES_DB: hasker_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rmq-data:/var/lib/rabbitmq
      - rmq-log:/var/log/rabbitmq
volumes:
  db-data:
  rmq-data:
  rmq-log: