# Generated by Django 4.1.2 on 2022-10-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0002_alter_post_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
    ]
