# Generated by Django 4.1.2 on 2022-10-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0003_remove_post_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcomments",
            old_name="author",
            new_name="post",
        ),
    ]
