# Generated by Django 4.1.2 on 2022-10-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0004_rename_author_postcomments_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcomments",
            old_name="post",
            new_name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="hasite.postcomments",
            ),
        ),
    ]
