# Generated by Django 4.1.2 on 2022-10-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0005_rename_post_postcomments_posts_post_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="postcomments",
            name="id",
        ),
        migrations.AlterField(
            model_name="postcomments",
            name="posts",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="hasite.post",
            ),
        ),
    ]
