# Generated by Django 4.1.2 on 2022-10-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0006_remove_post_comments_remove_postcomments_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcomments",
            name="posts",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="PostComments",
        ),
    ]
