# Generated by Django 4.1.2 on 2022-10-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0008_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostComments",
        ),
    ]
