# Generated by Django 4.1.2 on 2022-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0011_post_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomments",
            name="best",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="postcomments",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
