# Generated by Django 4.1.2 on 2022-10-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hasite", "0012_alter_postcomments_best_alter_postcomments_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomments",
            name="comment_author",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
