# Generated by Django 4.1.2 on 2022-10-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0013_postcomments_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="hasite.post",
            ),
        ),
    ]
