# Generated by Django 4.1.2 on 2022-10-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0015_votecount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="votecount",
            old_name="comment_count",
            new_name="count",
        ),
        migrations.RemoveField(
            model_name="votecount",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="votecount",
            name="post_count",
        ),
    ]
