# Generated by Django 4.1.2 on 2022-10-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0016_rename_comment_count_votecount_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="votecount",
            old_name="count",
            new_name="comment_count",
        ),
        migrations.AddField(
            model_name="votecount",
            name="comment",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="hasite.postcomments",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="votecount",
            name="post_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
