# Generated by Django 4.1.2 on 2022-10-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0017_rename_count_votecount_comment_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votecount",
            name="post",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="hasite.post"
            ),
        ),
        migrations.AlterField(
            model_name="votecount",
            name="post_count",
            field=models.IntegerField(default=0),
        ),
    ]
