# Generated by Django 4.1.2 on 2022-10-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0019_rename_votecount_votecommentcount_votepostcount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votecommentcount",
            name="post",
        ),
        migrations.RemoveField(
            model_name="votecommentcount",
            name="post_count",
        ),
    ]
