# Generated by Django 4.1.2 on 2022-10-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0020_remove_votecommentcount_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_tag", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hasite.posttags"
            ),
        ),
    ]
