# Generated by Django 4.1.2 on 2022-10-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0021_posttags_alter_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
