# Generated by Django 4.1.2 on 2022-10-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0022_remove_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hasite.posttags",
            ),
            preserve_default=False,
        ),
    ]
