# Generated by Django 4.1.2 on 2022-10-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0024_posttags_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
