# Generated by Django 4.1.2 on 2022-10-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hasite", "0025_remove_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttags",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="hasite.post",
            ),
        ),
    ]
